# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: detect-private-key
        language_version: python3

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=120", "--extend-ignore=E203,E266,E501,W503,F403,F401"]
        language_version: python3

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        args: ["--application-directories=.:app", "--py39-plus"]

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade

-   repo: https://github.com/psf/black
    rev: 24.1a1
    hooks:
    -   id: black
        args: [--safe]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        args: [--config-file, .mypy.ini]
